version: "3.8"
services:
  db:
    image: postgres:14.2-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: database_spring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    networks:
      - luis-network
volumes:
  localstack-vol:

networks:
  luis-network:
    driver: bridge
